# Generated by Django 5.0.14 on 2026-03-29 12:08

import employees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='barcode_image',
            field=models.FileField(blank=True, help_text='QR image encoding the barcode (for ID cards and scanning).', max_length=255, upload_to=employees.models._employee_barcode_upload),
        ),
        migrations.AlterField(
            model_name='employee',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, help_text='Leave empty when adding an employee; a unique code is generated automatically.', max_length=128, unique=True),
        ),
    ]
