# Generated by Django 5.2.4 on 2026-04-10 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_barcode_qr_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_time', models.TimeField(help_text='Expected check-in time.')),
                ('leave_time', models.TimeField(help_text='Earliest allowed check-out time.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='employees.employee')),
            ],
            options={
                'ordering': ['employee__name'],
            },
        ),
        migrations.CreateModel(
            name='LeavePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('approved_by', models.CharField(max_length=150)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_permissions', to='employees.employee')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('used_at__isnull', True)), fields=('employee', 'date'), name='unique_unused_leave_permission_per_day')],
            },
        ),
    ]
