# Generated by Django 5.2.4 on 2026-04-10 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employeeschedule_leavepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_time', models.TimeField(default=datetime.time(9, 0), help_text='Global expected check-in time.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='employeeschedule',
            name='report_time',
        ),
    ]
