# Generated by Django 5.2.4 on 2026-04-10 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_attendancepolicy_remove_employeeschedule_report_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancepolicy',
            name='checkout_time',
            field=models.TimeField(default=datetime.time(17, 0), help_text='Global earliest allowed check-out time.'),
        ),
        migrations.DeleteModel(
            name='EmployeeSchedule',
        ),
    ]
